### PR TITLE
added bundle

### PR DESCRIPTION
**Pull request by QmelZ**

### CODE REVIEW

**Comment by QmelZ** [comment]
@MEEPofFaith you are too slow come and merge this

**Comment by LixieWulf** [comment]
This does not remove file localizedName and description fields, which will override.

**Comment by QmelZ** [comment]
hm ok

**Comment by QmelZ** [comment]
done i guess

**Comment by LixieWulf** [comment]
Some things aren't changed - missed files from me being an idiot + 6.0 port still have "name:", and you may have missed statuses.
oh you got the name

**Comment by QmelZ** [comment]
*i actually somewhat fucked up with the last commit so i'll go try to revert that*

**Comment by LixieWulf** [comment]
*I CAN SEE THAT*

**Comment by QmelZ** [comment]
starting over, i fucked up way worse than i can fix

**Comment by LixieWulf** [comment]
I love how Mindustry's PRs are so organized and such and then this is just a clusterfuck.

**Pull request closed without merging**
