### PR TITLE
Prominence has more particles when firing, and prominence base

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by LixieWulf** [comment]
wheres the base

**Comment by ghost** [comment]
uh let me see

**Comment by ghost** [comment]
https://github.com/luxDuck/Exotic-Mod/blob/master/sprites/blocks/turrets/prominence-base.png

**Comment by ghost** [comment]
Here is what it looks like:

prominence

**Comment by ghost** [comment]
I  might make a sprite for the turret itself

**Comment by LixieWulf** [comment]
the base isnt included in the PR, and also does not match the sprite quality of the rest of the mod

**Comment by ghost** [comment]
Oh ok.

**Comment by ghost** [comment]
I tried to make warning lines, i'm not a good spriter

**Pull request closed without merging**
